# Generated by Django 3.1.4 on 2021-01-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0002_favoritejoke'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritejoke',
            unique_together={('user_id', 'joke_id')},
        ),
    ]
